#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
heroic_import_external.py
==========================

Companion to `heroic_categorize.py`.

Heroic only knows about Epic (legendary), GOG and Amazon (nile). Anything
else -- your Steam library, or games you have played without owning them on
PC -- does not exist inside Heroic, so it cannot be categorised.

This script creates those missing entries as "sideload" games (the same
mechanism as Heroic's own "Add Game" button), then produces a proposal CSV
you can feed straight into `heroic_categorize.py apply`.

Two subcommands:

  steam      Games you own on Steam that are absent from Heroic (KOTOR 2,
             Skyrim, Rise of Nations...). Each entry gets a small launcher
             script calling the `steam://rungameid/<appid>` protocol, so the
             game actually launches from Heroic.

  favorites  Games that are nowhere in your PC libraries but still matter
             (console favourites: Cyberpunk 2077, Mass Effect...). These are
             created as browser entries pointing at the Steam store page:
             not playable, but visible and categorisable as a reference.

Examples:
    python heroic_import_external.py steam --list steam-games.txt
    python heroic_import_external.py steam --list steam-games.txt --dry-run
    python heroic_import_external.py favorites --list favorites-not-on-pc.txt

then, with Heroic closed:
    python heroic_categorize.py apply proposal_steam.csv
    python heroic_categorize.py apply proposal_favorites.csv

The script is IDEMPOTENT: identifiers are derived from the title (uuid5), so
re-running never creates duplicates and never breaks categories you already
applied. sideload_apps/library.json is backed up before any write.

Runs on Linux, Windows and macOS. No external dependencies: Python 3 standard
library only.
"""

import argparse
import csv
import json
import os
import platform
import re
import shutil
import stat
import sys
import time
import urllib.parse
import uuid
from datetime import datetime

# Reuse everything that already exists instead of duplicating it.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import heroic_categorize as hc
except ImportError:
    print("heroic_categorize.py must sit in the same folder as this script.")
    sys.exit(1)


SIDELOAD_REL = os.path.join("sideload_apps", "library.json")
STEAM_CDN = "https://cdn.cloudflare.steamstatic.com/steam/apps"

# Fixed namespace: guarantees the same title always yields the same app_name,
# so a second run updates instead of duplicating.
NS_HEROIC = uuid.UUID("6f0a1c52-0d8e-5a3f-9b21-4c7e5d8a1b30")

# Lines skipped by default in a library list: demos, betas, tools, DLC,
# editors... everything that would just clutter the Heroic library.
DEFAULT_SKIP = [
    r"\bdemo\b",
    r"\bbeta\b",
    r"public test",
    r"\bsdk\b",
    r"\beditor\b",
    r"resource archiver",
    r"pre-game editor",
    r"\btest branch\b",
    r"soundtrack",
    r"\bost\b",
    r"art ?book",
    r"wallpaper",
    r"parts pack",
    r"free weekend",
    r"redistributables",
    r"\bdlc\b",
]


# ---------------------------------------------------------------------------
# Platform helpers
# ---------------------------------------------------------------------------


def heroic_platform():
    """The value Heroic expects in install.platform for a native binary."""
    system = platform.system()
    if system == "Windows":
        return "Windows"
    if system == "Darwin":
        return "Mac"
    return "linux"


def launcher_extension():
    return ".cmd" if platform.system() == "Windows" else ".sh"


def launcher_body(title, appid):
    """A tiny script that hands the steam:// URL to the OS. The exact form
    differs per platform, which is why this is not a one-liner."""
    system = platform.system()
    url = f"steam://rungameid/{appid}"
    if system == "Windows":
        return (
            "@echo off\r\n"
            f"rem Launches \"{title}\" via Steam (appid {appid}).\r\n"
            "rem Generated by heroic_import_external.py -- edit freely.\r\n"
            f"start \"\" \"{url}\"\r\n"
        )
    if system == "Darwin":
        return (
            "#!/usr/bin/env bash\n"
            f"# Launches \"{title}\" via Steam (appid {appid}).\n"
            "# Generated by heroic_import_external.py -- edit freely.\n"
            f"exec open \"{url}\"\n"
        )
    return (
        "#!/usr/bin/env bash\n"
        f"# Launches \"{title}\" via Steam (appid {appid}).\n"
        "# Generated by heroic_import_external.py -- edit freely.\n"
        f"exec steam {url}\n"
    )


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------


def title_key(title):
    """Forgiving comparison key: lowercase, unaccented, unpunctuated, without
    the marketing suffixes that differ from one store to the next."""
    t = hc.normalize(title)
    t = re.sub(r"[\u2122\u00ae]", " ", t)
    t = re.sub(
        r"\b(the|a|of|and|edition|definitive|remastered|remaster|complete|goty|"
        r"game of the year|enhanced|ultimate|special|deluxe|extended|classic|"
        r"anniversary|redux|reforged)\b",
        " ",
        t,
    )
    return re.sub(r"[^a-z0-9]+", " ", t).strip()


def app_name_for(title):
    """Stable 32-character hex identifier, matching Heroic's app_name format."""
    return uuid.uuid5(NS_HEROIC, title_key(title)).hex


def read_list(path):
    if not os.path.isfile(path):
        print(f"File not found: {path}")
        sys.exit(1)
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                # Some library exporters insert a stray space before an
                # apostrophe (e.g. "Lovers ' Smiles"), which throws off both
                # the Steam search and the dedup key. Tidy that up.
                line = re.sub(r"\s+(['\u2019])", r"\1", line)
                out.append(line)
    return out


def should_skip(title, patterns):
    low = title.lower()
    return any(re.search(p, low) for p in patterns)


def load_cache(path):
    if os.path.isfile(path):
        return hc.load_json(path) or {}
    return {}


def save_cache(cache, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)


def lookup_steam(title, cache, cache_path, lang, cc, delay):
    """Return the cache entry {appid, tags, genre} for a title, hitting
    Steam/SteamSpy only when necessary."""
    if title in cache:
        return cache[title], True
    found = hc.steam_find_appid(title, lang, cc)
    if not found:
        entry = {"appid": None, "tags": [], "genre": ""}
    else:
        appid, _score = found
        tags, genre = hc.steamspy_get_tags_and_genre(appid)
        entry = {"appid": appid, "tags": tags, "genre": genre}
        time.sleep(delay)
    cache[title] = entry
    save_cache(cache, cache_path)
    return entry, False


# ---------------------------------------------------------------------------
# Writing to sideload_apps/library.json
# ---------------------------------------------------------------------------


def load_sideload(heroic_dir):
    path = os.path.join(heroic_dir, SIDELOAD_REL)
    data = hc.load_json(path)
    if data is None:
        data = {"games": []}
    data.setdefault("games", [])
    return path, data


def art_for(appid):
    if not appid:
        return "", ""
    return (
        f"{STEAM_CDN}/{appid}/header.jpg",
        f"{STEAM_CDN}/{appid}/library_600x900.jpg",
    )


def steam_search_url(title):
    return "https://store.steampowered.com/search/?term=" + urllib.parse.quote(title)


def make_launcher(launch_dir, title, appid):
    """Write the small launcher script and return its absolute path."""
    os.makedirs(launch_dir, exist_ok=True)
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", title).strip("_") or str(appid)
    path = os.path.join(launch_dir, safe + launcher_extension())
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(launcher_body(title, appid))
    if platform.system() != "Windows":
        os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def build_entry(title, appid, kind, launcher_path=None, launch_dir=None):
    """Build a sideload entry in the shape Heroic expects.

    kind == "steam" with an appid  : genuinely launchable (executable = launcher script)
    kind == "steam" without an appid : no Steam page was found automatically,
        so there is nothing to launch yet -- created as a browser placeholder
        pointing at a Steam *search* for the title, so you can look it up,
        fix the title, or add the real launcher by hand later.
    kind == "favorites"             : browser entry pointing at the Steam store page
        (or a search page, if no exact page was found -- e.g. games that only
        ever existed on a console or another launcher, with no Steam page at all)
    """
    app_name = app_name_for(title)
    cover, square = art_for(appid)
    store_url = f"https://store.steampowered.com/app/{appid}" if appid else ""

    entry = {
        "runner": "sideload",
        "app_name": app_name,
        "title": title,
        "art_cover": cover,
        "art_square": square,
        "is_installed": True,
        "canRunOffline": kind == "steam" and bool(appid),
    }

    if kind == "steam" and appid:
        entry["install"] = {
            "executable": launcher_path,
            "platform": heroic_platform(),
            "is_installed": True,
        }
        entry["folder_name"] = launch_dir
        entry["description"] = "Steam game imported into Heroic for categorisation."
    elif kind == "steam":
        entry["install"] = {"platform": "Browser", "is_installed": True}
        entry["browserUrl"] = steam_search_url(title)
        entry["description"] = (
            "No Steam page found automatically -- placeholder pointing at a "
            "Steam search for this title. Fix the title and re-run, or "
            "replace this entry by hand once you have found the right game."
        )
    else:
        entry["install"] = {"platform": "Browser", "is_installed": True}
        entry["browserUrl"] = store_url or steam_search_url(title)
        entry["description"] = "Reference entry (not owned on PC) -- opens the Steam store page."

    return entry


def merge_sideload(data, entries):
    """Merge by app_name: update what exists, append the rest."""
    by_app = {g.get("app_name"): i for i, g in enumerate(data["games"]) if g.get("app_name")}
    added = updated = 0
    for e in entries:
        idx = by_app.get(e["app_name"])
        if idx is None:
            data["games"].append(e)
            by_app[e["app_name"]] = len(data["games"]) - 1
            added += 1
        else:
            data["games"][idx].update(e)
            updated += 1
    return added, updated


def write_sideload(path, data):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    if os.path.isfile(path):
        backup = path + ".bak-" + datetime.now().strftime("%Y%m%d-%H%M%S")
        shutil.copy2(path, backup)
        print(f"Backed up to: {backup}")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def write_proposal(rows, output):
    with open(output, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["title", "app_name", "runner", "heroic_id", "category", "matched_on", "top_tags"],
        )
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Shared core of both subcommands
# ---------------------------------------------------------------------------


def run_import(args, kind):
    heroic_dir = args.heroic_dir
    if not os.path.isdir(heroic_dir):
        print(f"Heroic folder not found: {heroic_dir}")
        print("Point at it with --heroic-dir.")
        sys.exit(1)

    if not args.dry_run and not args.force and hc.heroic_still_running():
        print("!! Heroic is still running (often minimised to the system tray).")
        print("   It would overwrite these changes. Close it first:")
        if platform.system() == "Windows":
            print("       taskkill /F /IM Heroic.exe /T")
        else:
            print("       pkill -f -i heroic")
        print("   then run again. (--force to override, --dry-run to test.)")
        sys.exit(1)

    mapping = hc.load_mapping(args.mapping)
    print(f"{len(mapping)} tag -> category rules loaded.")

    # 1. What Heroic already knows about
    print("Reading the Heroic library...")
    library = hc.collect_library(heroic_dir)
    known = {title_key(g["title"]) for g in library}
    print(f"{len(library)} games already present in Heroic.")

    # 2. What else to skip (other stores, for the favorites subcommand)
    excluded = set()
    for path in args.exclude_list or []:
        for t in read_list(path):
            excluded.add(title_key(t))
    if excluded:
        print(f"{len(excluded)} titles loaded from the exclusion lists.")

    skip_patterns = list(DEFAULT_SKIP)
    if args.no_default_skip:
        skip_patterns = []
    if args.skip:
        skip_patterns += [args.skip]

    # 3. Filter the input list
    wanted = read_list(args.list)
    todo, ignored = [], []
    for title in wanted:
        key = title_key(title)
        if not key:
            continue
        if should_skip(title, skip_patterns):
            ignored.append((title, "filtered out (demo/tool/DLC)"))
        elif key in known:
            ignored.append((title, "already in Heroic"))
        elif key in excluded:
            ignored.append((title, "present in another library"))
        else:
            todo.append(title)

    print(f"{len(todo)} games to import, {len(ignored)} skipped.")
    if args.verbose:
        for title, why in ignored:
            print(f"  - {title}  [{why}]")
    if args.limit:
        todo = todo[: args.limit]
        print(f"Capped at {len(todo)} for this run.")
    if not todo:
        print("Nothing to do.")
        return

    # 4. Steam lookup + categorisation
    cache = load_cache(args.cache)
    launch_dir = os.path.abspath(os.path.expanduser(args.launchers_dir))
    entries, rows, unmatched = [], [], []

    for i, title in enumerate(todo, 1):
        print(f"[{i}/{len(todo)}] {title}", end=" ... ")
        entry, cached = lookup_steam(title, cache, args.cache, args.lang, args.cc, args.delay)
        appid = entry.get("appid")
        print("(cached)" if cached else (f"appid={appid}" if appid else "no Steam match"))

        if not appid:
            unmatched.append(title)
            if args.skip_unmatched:
                continue

        launcher = None
        if kind == "steam" and appid and not args.no_launcher:
            launcher = make_launcher(launch_dir, title, appid)

        game = build_entry(title, appid, kind, launcher, launch_dir)
        entries.append(game)

        categories, matched_on = hc.pick_categories(
            entry.get("tags", []), entry.get("genre", ""), mapping, args.max_categories
        )
        for extra in args.extra_category or []:
            if extra not in categories:
                categories.insert(0, extra)

        rows.append(
            {
                "title": title,
                "app_name": game["app_name"],
                "runner": "sideload",
                "heroic_id": f"{game['app_name']}_sideload",
                "category": "; ".join(categories),
                "matched_on": "; ".join(matched_on),
                "top_tags": ", ".join(entry.get("tags", [])[:6]),
            }
        )

    # 5. Write everything out
    write_proposal(rows, args.output)
    print()
    print(f"Proposal written: {args.output}  ({len(rows)} rows)")

    sideload_path, data = load_sideload(heroic_dir)
    added, updated = merge_sideload(data, entries)

    if args.dry_run:
        print(f"[dry-run] {added} entries would be added, {updated} updated "
              f"in {sideload_path}. Nothing was written.")
    else:
        write_sideload(sideload_path, data)
        print(f"{added} entries added, {updated} updated in {sideload_path}")
        if kind == "steam" and not args.no_launcher:
            print(f"Launcher scripts generated in: {launch_dir}")

    if unmatched:
        print()
        if args.skip_unmatched:
            print(f"{len(unmatched)} title(s) with no Steam match, skipped entirely "
                  f"(--skip-unmatched): not in the CSV, not added to Heroic.")
        elif kind == "steam":
            print(f"{len(unmatched)} title(s) with no Steam match: added anyway, as a "
                  f"non-launchable placeholder pointing at a Steam search, with an "
                  f"empty category to fill in by hand:")
        else:
            print(f"{len(unmatched)} title(s) with no Steam match (often games with no "
                  f"Steam page at all -- Battle.net, a console, a launcher of their own): "
                  f"added with an empty category to fill in by hand:")
        for t in unmatched:
            print(f"  - {t}")

    print()
    print("Review/fix the 'category' column, then with Heroic closed:")
    print(f"    python heroic_categorize.py apply {args.output}")


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------


def cmd_steam(args):
    run_import(args, "steam")


def cmd_favorites(args):
    run_import(args, "favorites")


def add_common(p, default_output, default_extra):
    p.add_argument("--list", required=True, help="Text file, one title per line")
    p.add_argument("--exclude-list", action="append", default=[],
                   help="List of titles NOT to import (repeatable)")
    p.add_argument("--mapping", default="mapping.json", help="Tag -> category mapping file")
    p.add_argument("--cache", default="steam_cache.json", help="Steam/SteamSpy cache, shared with scan")
    p.add_argument("--output", default=default_output, help="Proposal CSV to generate")
    p.add_argument("--extra-category", action="append", default=list(default_extra),
                   help="Category added to every game (repeatable)")
    p.add_argument("--max-categories", type=int, default=5, help="Max automatic categories per game")
    p.add_argument("--lang", default="english", help="Language requested from Steam")
    p.add_argument("--cc", default="us", help="Steam country code")
    p.add_argument("--delay", type=float, default=1.0, help="Delay between two SteamSpy calls")
    p.add_argument("--skip", default=None, help="Additional regex pattern to skip")
    p.add_argument("--no-default-skip", action="store_true",
                   help="Disable the demo/beta/tool/DLC filter")
    p.add_argument("--launchers-dir", default="~/heroic-steam-launchers",
                   help="Folder for the generated Steam launcher scripts")
    p.add_argument("--skip-unmatched", action="store_true",
                   help="Drop titles with no Steam match entirely instead of adding "
                        "them as an uncategorised placeholder")
    p.add_argument("--limit", type=int, default=0, help="Cap the number of games (testing)")
    p.add_argument("--dry-run", action="store_true", help="Do not write to Heroic, just show the result")
    p.add_argument("--force", action="store_true", help="Ignore the running-Heroic detection")
    p.add_argument("--verbose", action="store_true", help="List the skipped titles")


def build_parser():
    parser = argparse.ArgumentParser(
        description="Import external games (Steam, or not owned at all) into Heroic so they can be categorised."
    )
    parser.add_argument("--heroic-dir", default=hc.default_heroic_dir(),
                        help="Heroic configuration folder")
    sub = parser.add_subparsers(dest="command", required=True)

    p_steam = sub.add_parser("steam", help="Import Steam games missing from Heroic (launchable)")
    add_common(p_steam, "proposal_steam.csv", ["Steam"])
    p_steam.add_argument("--no-launcher", action="store_true",
                         help="Do not generate launcher scripts (reference-only entries)")
    p_steam.set_defaults(func=cmd_steam)

    p_fav = sub.add_parser("favorites",
                           help="Import games not owned on PC (favourites, for reference)")
    add_common(p_fav, "proposal_favorites.csv", ["Favorites"])
    p_fav.set_defaults(func=cmd_favorites, no_launcher=True)

    return parser


def main():
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
